// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { UploadCoilsData, UploadCoilsErrors, UploadCoilsResponses, UploadVmecData, UploadVmecErrors, UploadVmecResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate a magnet_set STEP from a MAKEGRID coils file
 *
 * Equivalent to the `magnet` subcommand. Accepts a MAKEGRID-format coils
 * file (e.g. `coils.example`) and returns 2 artifacts: a STEP of the swept
 * rectangular-section coils and its CSV point cloud.
 */
export const uploadCoils = <ThrowOnError extends boolean = true>(options: Options<UploadCoilsData, ThrowOnError>) => (options.client ?? client).post<UploadCoilsResponses, UploadCoilsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/magnet',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Generate in-vessel components from a VMEC NetCDF file
 *
 * Equivalent to the `vessel` subcommand. Accepts a VMEC `wout_*.nc` file
 * and returns 12 artifacts: 6 STEP solids (chamber, first_wall, breeder,
 * back_wall, shield, vacuum_vessel) and their corresponding CSV point
 * clouds.
 */
export const uploadVmec = <ThrowOnError extends boolean = true>(options: Options<UploadVmecData, ThrowOnError>) => (options.client ?? client).post<UploadVmecResponses, UploadVmecErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/vessel',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
