// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Error = {
    message: string;
};

export type FileEntry = {
    /**
     * Output filename, e.g. `chamber.step` or `magnet_set.csv`.
     */
    filename: string;
    /**
     * MIME type hint for the payload (e.g. `model/step`, `text/csv`).
     */
    content_type: string;
    /**
     * Base64-encoded file contents.
     */
    data: string;
};

export type FileList = Array<FileEntry>;

export type MagnetUpload = {
    /**
     * MAKEGRID-format coils file (text).
     */
    file: Blob | File;
};

export type VesselUpload = {
    /**
     * VMEC NetCDF-3 64-bit offset file (wout_*.nc).
     */
    file: Blob | File;
};

export type UploadCoilsData = {
    body: MagnetUpload;
    path?: never;
    query?: {
        /**
         * Rectangular cross-section width [m]. Default 0.4 m matches parastell.
         */
        width?: number;
        /**
         * Rectangular cross-section thickness [m]. Default 0.5 m matches parastell.
         */
        thickness?: number;
        /**
         * Toroidal extent [deg]. 360 keeps all coils; values below 360 are reserved for future use.
         */
        toroidal_extent?: number;
    };
    url: '/magnet';
};

export type UploadCoilsErrors = {
    /**
     * Invalid input file or parameters.
     */
    400: Error;
    /**
     * Processing failure.
     */
    500: Error;
};

export type UploadCoilsError = UploadCoilsErrors[keyof UploadCoilsErrors];

export type UploadCoilsResponses = {
    /**
     * Generated in-vessel artifacts (6 STEP + 6 CSV).
     */
    200: FileList;
};

export type UploadCoilsResponse = UploadCoilsResponses[keyof UploadCoilsResponses];

export type UploadVmecData = {
    body: VesselUpload;
    path?: never;
    query?: {
        /**
         * Reference flux surface. Parastell default 1.08 (just outside the LCFS).
         */
        wall_s?: number;
        /**
         * Unit scaling factor. VMEC is in meters; 100 converts to centimeters to match the parastell default.
         */
        scale?: number;
    };
    url: '/vessel';
};

export type UploadVmecErrors = {
    /**
     * Invalid input file or parameters.
     */
    400: Error;
    /**
     * Processing failure.
     */
    500: Error;
};

export type UploadVmecError = UploadVmecErrors[keyof UploadVmecErrors];

export type UploadVmecResponses = {
    /**
     * Generated in-vessel artifacts (6 STEP + 6 CSV).
     */
    200: FileList;
};

export type UploadVmecResponse = UploadVmecResponses[keyof UploadVmecResponses];
